language: c
os:
 - linux
env:
 matrix:
  - PYTHON_VERSION=3.7
 global:
  - CONDA_DEPENDENCIES="nodejs numpy nomkl jupyterlab>=0.34"
  - CONDA_CHANNELS="conda-forge"
  - CONDA_CHANNEL_PRIORITY=True
  - SETUP_XVFB=True

# matrix:
#   allow_failures:
#     env: PYTHON_VERSION=3.6

before_install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - conda info -a

install:
  - pip install -e .[test]

script:

  # Run test suite
  - pytest --cov glue_jupyter glue_jupyter -p no:warnings

  # Check notebooks
  - pip install astroquery pyyaml
  - python .validate-notebooks.py

  # Test documentation build
  - pip install -e .[docs]
  - cd docs
  - make html
  - cd ..

  # Publish documentation on gh-pages
  - ./.deploy_docs.sh

after_success:
  - codecov
